name: Build firmware

on:
  push:
  workflow_dispatch:

jobs:
  build-single:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: '8.0.1'

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get -y install ninja-build gcc-arm-none-eabi

      - name: Setup environment
        run: |
          BUILD_SUFFIX=ci-$(date '+%Y%m%d')-$(git rev-parse --short HEAD)
          VERSION=$(grep project CMakeLists.txt|awk -F VERSION '{ gsub(/[ \t)]/, "", $2); print $2 }')
          echo "BUILD_NAME=inav-${VERSION}-${BUILD_SUFFIX}" >> $GITHUB_ENV
          echo "NUM_CORES=$(grep processor /proc/cpuinfo | wc -l)" >> $GITHUB_ENV

      - name: Build target FLYWOOF7DUAL
        run: |
          mkdir -p build && cd build
          cmake -DWARNINGS_AS_ERRORS=OFF -DMAIN_COMPILE_OPTIONS=-pipe -G Ninja ..
          ninja -j${{ env.NUM_CORES }} FLYWOOF7DUAL

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BUILD_NAME }}-FLYWOOF7DUAL
          path: ./build/inav_*.hex
          retention-days: 1
